name: Предложение
description: Улучшение сборщика, данных или API
title: 'feature: '
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу нужно решить
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое поведение
    validations:
      required: true
